version: '2.4'
services:
  web:
    container_name: kevinlarkin-web
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    image: kevinlarkin-web
    volumes:
      - ./src:/code/public
    ports:
      - "80:80"
