version: '2.4'
services:
  web:
    container_name: kevinlarkin-web
    image: $CONTAINER_FRONTEND_PROD
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: kevinlarkin
