version: '2.4'
services:
  web:
    container_name: kevinlarkin-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web-production
    restart: always
    environment:
      VIRTUAL_HOST: www.kevinlarkin.co.uk
      LETSENCRYPT_HOST: www.kevinlarkin.co.uk
      LETSENCRYPT_EMAIL:
  redirect:
    container_name: kevinlarkin-redirect
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: kevinlarkin.co.uk
      LETSENCRYPT_HOST: kevinlarkin.co.uk
      LETSENCRYPT_EMAIL:
      REDIRECT_TARGET: www.kevinlarkin.co.uk

networks:
  default:
    name: kevinlarkin
